version: '3'
services:
  eatceed-mariadb:
    image: mariadb:10.6
    container_name: gaebaljip-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./resources/gaebaljip-develop-environment/mariadb-conf:/etc/mysql/conf.d
      - ./resources/gaebaljip-develop-environment/mariadb-init:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MARIADB_ROOT_PASSWORD=eatceed
      - MYSQL_DATABASE=gaebaljip
      - MYSQL_USER=gaebaljip-dev
      - MYSQL_PASSWORD=gaebaljip-dev
    networks:
      - gaebaljip-network

  eatceed-redis:
    image: redis:alpine
    container_name: gaebaljip-redis
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - gaebaljip-network

  eatceed-backend:
    image: hwangdaesun/gaebaljip-dev:latest
    container_name: gaebaljip-spring
    ports:
      - 8080:8080
    depends_on:
      - eatceed-mariadb
      - eatceed-redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://gaebaljip-mariadb:3306/gaebaljip?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=gaebaljip-dev
      - SPRING_DATASOURCE_PASSWORD=gaebaljip-dev
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CLOUD_AWS_ACCESS_KEY=${CLOUD_AWS_ACCESS_KEY}
      - CLOUD_AWS_SECRET_KEY=${CLOUD_AWS_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SES_MAIL_ADDRESS=${SES_MAIL_ADDRESS}
      - ENCRYPTION_SPEC=${ENCRYPTION_SPEC}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - ENCRYPTION_ALGORITHM=${ENCRYPTION_ALGORITHM}
      - SPRING_REDIS_HOST=gaebaljip-redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=${SPRING_REDIS_PASSWORD}
      - SCHEDULER_NUTRITION_CACHE_UPDATE=${SCHEDULER_NUTRITION_CACHE_UPDATE}
      - APP_VERSION=${APP_VERSION}
      - EXCEED_POLICY_URL=${EXCEED_POLICY_URL}
      - EXCEED_CONTACT_EMAIL=${EXCEED_CONTACT_EMAIL}
    networks:
      - gaebaljip-network
    restart:  "no"

networks:
  gaebaljip-network:
