version: '3'
services:
  eatceed-backend:
    image: hwangdaesun/gaebaljip-prod:latest
    container_name: gaebaljip-spring
    ports:
      - 8080:8080
    environment:
      - RDS_DATABASE_ENDPOINT=${RDS_DATABASE_ENDPOINT}
      - RDS_PORT=${RDS_PORT}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_DATABASE_USERNAME=${RDS_DATABASE_USERNAME}
      - RDS_DATABASE_PASSWORD=${RDS_DATABASE_PASSWORD}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CLOUD_AWS_ACCESS_KEY=${CLOUD_AWS_ACCESS_KEY}
      - CLOUD_AWS_SECRET_KEY=${CLOUD_AWS_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SES_MAIL_ADDRESS=${SES_MAIL_ADDRESS}
      - ENCRYPTION_SPEC=${ENCRYPTION_SPEC}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - ENCRYPTION_ALGORITHM=${ENCRYPTION_ALGORITHM}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SCHEDULER_NUTRITION_CACHE_UPDATE=${SCHEDULER_NUTRITION_CACHE_UPDATE}
      - APP_VERSION=${APP_VERSION}
      - EXCEED_POLICY_URL=${EXCEED_POLICY_URL}
      - EXCEED_CONTACT_EMAIL=${EXCEED_CONTACT_EMAIL}
    networks:
      - gaebaljip-network
    restart:  "always"

networks:
  gaebaljip-network:
