### Application Version ###
applicationVersion=1.0.0

### Project Configs ###
projectGroup=com.gaebaljip
javaVersion=17

### Spring Dependencies ###
springBootVersion=2.7.11
springDependencyManagementVersion=1.1.4

### QueryDSL ###
queryDSLVersion=5.0.0

### TestContainer ###
testContainersVersion=1.19.8
